spring:
  application:
    name: study
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  sql:
    init:
      platform: h2
  h2:
    console:
      enabled: true
      path: /h2-console